Nc news 3
amy-baker/news pull request #3
Opened 2023-08-14 15:01 UTC by amy-baker

2023-08-14 15:32 UTC, poppymcd requested changes
Just a few changes to make before merging - once you've made your changes, put in another pr tomorrow and we'll have another look 😄

2023-08-14 15:32 UTC, poppymcd commented on __tests__/app.test.js
> +            // console.log(endpoints, "<endpoints")
Remember to remove console.logs and commented out code before pushing your code

2023-08-14 15:32 UTC, nc-poppy-m commented on db/model.js
> +    try {
Try and be consistent - in your previous model you use a .then block so it's good practice to use the same syntax :)

2023-08-14 15:32 UTC, poppymcd commented on db/model.js
> +const selectAllEndpoints = async () => {
As we are not interacting with the database, this should be handled in the controller

2023-08-14 15:32 UTC, poppymcd commented on __tests__/app.test.js
> +                for (let endpointInstance in endpoints) {
This test will never fail, so when you write a new endpoint, how could you check this has been updated?

2023-08-15 09:09 UTC, mezzDavies approved these changes
Approved 😄 IF you wanted to refactor you could simply require the endpoint.json file into the controller file as well as the test file (without fsread) and assert that what is sent back from the endpoint.controller is equal to the file in the tests.

2023-08-15 09:11 UTC, merged